<?php
declare(strict_types=1); require __DIR__.'/_bootstrap.php';
$d=body();$code=clean_code($d['room_code']??'');$pid=clean_id($d['player_id']??'');$token=(string)($d['player_token']??'');$action=(string)($d['action']??'');$payload=is_array($d['payload']??null)?$d['payload']:[];
with_room($code,true,function(array $room)use($pid,$token,$action,$payload){
  $pi=auth_in_room($room,$pid,$token);$p=$room['players'][$pi];$phase=(string)($room['phase']??'lobby');$s=$room['state']??[];$players=$room['players'];
  switch($action){
    case 'start_game': require_host($p);if($phase!=='lobby')fail('اللعبة بدأت بالفعل',409);if(count($players)<MUNDAS_MIN_PLAYERS)fail('تحتاجون 3 لاعبين على الأقل',422);$cats=array_values(array_unique(array_filter(array_map('strval',$payload['categories']??[]))));if(!$cats)fail('اختر فئة واحدة على الأقل',422);$s=pick_round($cats,$players);$phase='role_reveal';foreach($room['players'] as &$pp){$pp['role_seen']=false;$pp['voted']=false;}unset($pp);break;
    case 'role_seen': if($phase!=='role_reveal')fail('ليس وقت كشف الدور',409);$room['players'][$pi]['role_seen']=true;$all=true;foreach($room['players'] as $pp)if(empty($pp['role_seen'])){$all=false;break;}if($all)$phase='drawing';break;
    case 'draw_stroke': if($phase!=='drawing')fail('ليس وقت الرسم',409);$order=$s['turn_order']??[];$ti=(int)($s['turn_index']??0);if(($order[$ti]??null)!==$pid)fail('ليس دورك بالرسم',403);$stroke=$payload['stroke']??null;if(!is_array($stroke))fail('بيانات الرسم غير صحيحة');$pts=$stroke['points']??[];if(!is_array($pts)||count($pts)<2||count($pts)>MUNDAS_MAX_POINTS_PER_STROKE)fail('خط الرسم غير صالح');$clean=[];foreach($pts as $pt){if(!is_array($pt)||count($pt)<2)continue;$clean[]=[max(0,min(1,(float)$pt[0])),max(0,min(1,(float)$pt[1]))];}if(count($clean)<2)fail('خط الرسم فارغ');$strokes=$s['strokes']??[];if(count($strokes)>=MUNDAS_MAX_STROKES)fail('وصل الرسم للحد الأقصى');$strokes[]=['points'=>$clean,'color'=>(int)($stroke['color']??0xFF183330),'width'=>max(2,min(14,(float)($stroke['width']??5))),'owner'=>$pid];$s['strokes']=$strokes;break;
    case 'finish_turn': if($phase!=='drawing')fail('ليس وقت الرسم',409);$order=$s['turn_order']??[];$ti=(int)($s['turn_index']??0);if(($order[$ti]??null)!==$pid)fail('ليس دورك',403);if($ti>=count($order)-1)$phase='discussion';else$s['turn_index']=$ti+1;break;
    case 'start_voting': require_host($p);if($phase!=='discussion')fail('ليس وقت التصويت',409);$phase='voting';$s['votes']=[];$s['runoff_candidate_ids']=[];foreach($room['players'] as &$pp)$pp['voted']=false;unset($pp);break;
    case 'vote': if($phase!=='voting')fail('التصويت غير مفتوح',409);if(!empty($p['voted']))fail('تم تسجيل صوتك مسبقاً',409);$target=(string)($payload['target_player_id']??'');if($target===$pid)fail('لا يمكنك التصويت لنفسك');$ids=array_column($players,'id');if(!in_array($target,$ids,true))fail('اللاعب المختار غير موجود');$runoff=$s['runoff_candidate_ids']??[];if($runoff&&!in_array($target,$runoff,true))fail('التصويت الفاصل محصور بالمتعادلين');$votes=$s['votes']??[];$votes[$pid]=$target;$s['votes']=$votes;$room['players'][$pi]['voted']=true;if(count($votes)>=count($players)){$counts=[];foreach($votes as $v)$counts[$v]=($counts[$v]??0)+1;$max=max($counts);$leaders=array_keys(array_filter($counts,fn($n)=>$n===$max));if(count($leaders)>1){$s['runoff_candidate_ids']=$leaders;$s['votes']=[];foreach($room['players'] as &$pp)$pp['voted']=false;unset($pp);}else{$s['accused_player_id']=$leaders[0];$s['runoff_candidate_ids']=[];$phase='reveal';}}break;
    case 'reveal_result': require_host($p);if($phase!=='reveal')fail('لا توجد نتيجة للكشف',409);if(($s['accused_player_id']??null)===($s['imposter_id']??null))$phase='imposter_guess';else{$s['winner']='imposter';$phase='game_over';}break;
    case 'imposter_guess': if($phase!=='imposter_guess')fail('ليس وقت التخمين',409);if($pid!==($s['imposter_id']??null))fail('التخمين للمندس فقط',403);$g=trim((string)($payload['guess']??''));if($g==='')fail('اكتب تخمينك');$ok=normalize_ar($g)===normalize_ar((string)($s['secret_word']??''));$s['guess_correct']=$ok;$s['winner']=$ok?'imposter':'crew';$phase='game_over';break;
    case 'replay': require_host($p);if($phase!=='game_over')fail('الجولة لم تنته بعد',409);$cats=$s['selected_categories']??[];$s=pick_round($cats,$players);$phase='role_reveal';foreach($room['players'] as &$pp){$pp['role_seen']=false;$pp['voted']=false;}unset($pp);break;
    default: fail('إجراء غير معروف',400);
  }
  $room['phase']=$phase;$room['state']=$s;return ['__room'=>$room];
});
out(['ok'=>true]);
